<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="DoctrineTest\InstantiatorTestAsset\FinalExceptionAsset" namespace="DoctrineTest\InstantiatorTestAsset" name="FinalExceptionAsset" abstract="false" final="true" start="30" end="41">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset" file="FinalExceptionAsset.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset/FinalExceptionAsset.php" size="1470" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="ce12472e87e814bfd12eeb0f8758806e91da1601" relative="vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset/FinalExceptionAsset.php"/>
  <docblock>
    <description compact="Test asset that extends an internal PHP base exception"/>
    <author value="Marco Pivetta &lt;ocramius@gmail.com&gt;"/>
  </docblock>
  <extends full="Exception" namespace="" name="Exception"/>
  <constructor name="__construct" start="37" end="40" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Constructor - should not be called"/>
      <throws type="object">
        <type full="BadMethodCallException" namespace="" name="BadMethodCallException"/>
      </throws>
    </docblock>
  </constructor>
</class>
