<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="DoctrineTest\InstantiatorTestAsset\ExceptionAsset" namespace="DoctrineTest\InstantiatorTestAsset" name="ExceptionAsset" abstract="false" final="false" start="30" end="41">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset" file="ExceptionAsset.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset/ExceptionAsset.php" size="1459" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="2ca083f9b66dfd83cc2c0e7a6ee95eb3519cfc3d" relative="vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTestAsset/ExceptionAsset.php"/>
  <docblock>
    <description compact="Test asset that extends an internal PHP base exception"/>
    <author value="Marco Pivetta &lt;ocramius@gmail.com&gt;"/>
  </docblock>
  <extends full="Exception" namespace="" name="Exception"/>
  <constructor name="__construct" start="37" end="40" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Constructor - should not be called"/>
      <throws type="object">
        <type full="BadMethodCallException" namespace="" name="BadMethodCallException"/>
      </throws>
    </docblock>
  </constructor>
</class>
