<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Framework_ExceptionWrapper" namespace="" name="PHPUnit_Framework_ExceptionWrapper" abstract="false" final="false" start="22" end="91">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework" file="ExceptionWrapper.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework/ExceptionWrapper.php" size="2200" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="f13a1e110f8e02feadc353109b655aeadbdb9121" relative="vendor/phpunit/phpunit/src/Framework/ExceptionWrapper.php"/>
  <docblock>
    <description compact="Wraps Exceptions thrown by code under test.">Re-instantiates Exceptions thrown by user-space code to retain their original
class names, properties, and stack traces (but without arguments).

Unlike PHPUnit_Framework_Exception, the complete stack of previous Exceptions
is processed.</description>
    <since value="Class available since Release 4.3.0"/>
  </docblock>
  <extends full="PHPUnit_Framework_Exception" namespace="" name="PHPUnit_Framework_Exception"/>
  <member name="classname" visibility="protected" line="27">
    <docblock>
      <description/>
      <var type="string"/>
    </docblock>
  </member>
  <member name="previous" visibility="protected" line="32">
    <docblock>
      <description/>
      <var type="object">
        <type full="PHPUnit_Framework_ExceptionWrapper|null" namespace="" name="PHPUnit_Framework_ExceptionWrapper|null"/>
      </var>
    </docblock>
  </member>
  <constructor name="__construct" start="37" end="56" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <param type="object" variable="$e">
        <type full="Throwable|Exception" namespace="" name="Throwable|Exception"/>
      </param>
    </docblock>
    <parameter name="e" byreference="false" type="{unknown}"/>
    <inline>
      <comment value="PDOException::getCode() is a string." line="39"/>
      <comment value="@see http://php.net/manual/en/class.pdoexception.php#95812" line="40"/>
    </inline>
  </constructor>
  <method name="getClassname" start="61" end="64" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <return type="string"/>
    </docblock>
  </method>
  <method name="getPreviousWrapped" start="69" end="72" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <return type="object">
        <type full="PHPUnit_Framework_ExceptionWrapper" namespace="" name="PHPUnit_Framework_ExceptionWrapper"/>
      </return>
    </docblock>
  </method>
  <method name="__toString" start="77" end="90" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <return type="string"/>
    </docblock>
  </method>
</class>
