<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Framework_TestFailure" namespace="" name="PHPUnit_Framework_TestFailure" abstract="false" final="false" start="16" end="167">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework" file="TestFailure.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework/TestFailure.php" size="4123" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="8a7faa4680e03c778ca0eee31a97ba6dedcc8462" relative="vendor/phpunit/phpunit/src/Framework/TestFailure.php"/>
  <docblock>
    <description compact="A TestFailure collects a failed test together with the caught exception."/>
    <since value="Class available since Release 2.0.0"/>
  </docblock>
  <member name="testName" visibility="private" line="21">
    <docblock>
      <description/>
      <var type="string"/>
    </docblock>
  </member>
  <member name="failedTest" visibility="protected" line="26">
    <docblock>
      <description/>
      <var type="object">
        <type full="PHPUnit_Framework_Test|null" namespace="" name="PHPUnit_Framework_Test|null"/>
      </var>
    </docblock>
  </member>
  <member name="thrownException" visibility="protected" line="31">
    <docblock>
      <description/>
      <var type="object">
        <type full="Exception" namespace="" name="Exception"/>
      </var>
    </docblock>
  </member>
  <constructor name="__construct" start="39" end="50" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Constructs a TestFailure with the given test and exception."/>
      <param type="object" variable="$failedTest">
        <type full="PHPUnit_Framework_Test" namespace="" name="PHPUnit_Framework_Test"/>
      </param>
      <param type="object" variable="$thrownException">
        <type full="Exception" namespace="" name="Exception"/>
      </param>
    </docblock>
    <parameter name="failedTest" byreference="false" type="object">
      <type full="PHPUnit_Framework_Test" namespace="" name="PHPUnit_Framework_Test"/>
    </parameter>
    <parameter name="thrownException" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </constructor>
  <method name="toString" start="57" end="64" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns a short description of the failure."/>
      <return type="string"/>
    </docblock>
  </method>
  <method name="getExceptionAsString" start="73" end="76" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns a description for the thrown exception."/>
      <return type="string"/>
      <since value="Method available since Release 3.4.0"/>
    </docblock>
  </method>
  <method name="exceptionToString" start="87" end="108" abstract="false" final="false" static="true" visibility="public">
    <docblock>
      <description compact="Returns a description for an exception."/>
      <param type="object" variable="$e">
        <type full="Exception" namespace="" name="Exception"/>
      </param>
      <return type="string"/>
      <since value="Method available since Release 3.2.0"/>
    </docblock>
    <parameter name="e" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </method>
  <method name="getTestName" start="117" end="120" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns the name of the failing test (including data set, if any)."/>
      <return type="string"/>
      <since value="Method available since Release 4.3.0"/>
    </docblock>
  </method>
  <method name="failedTest" start="132" end="135" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns the failing test.">Note: The test object is not set when the test is executed in process
isolation.</description>
      <see value="PHPUnit_Framework_Exception"/>
      <return type="object">
        <type full="PHPUnit_Framework_Test|null" namespace="" name="PHPUnit_Framework_Test|null"/>
      </return>
    </docblock>
  </method>
  <method name="thrownException" start="142" end="145" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Gets the thrown exception."/>
      <return type="object">
        <type full="Exception" namespace="" name="Exception"/>
      </return>
    </docblock>
  </method>
  <method name="exceptionMessage" start="152" end="155" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns the exception's message."/>
      <return type="string"/>
    </docblock>
  </method>
  <method name="isFailure" start="163" end="166" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns true if the thrown exception is of type AssertionFailedError."/>
      <return type="object">
        <type full="bool" namespace="" name="bool"/>
      </return>
    </docblock>
  </method>
</class>
