<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Exception\ContextErrorException" namespace="Symfony\Component\Debug\Exception" name="ContextErrorException" abstract="false" final="false" start="19" end="36">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Exception" file="ContextErrorException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Exception/ContextErrorException.php" size="875" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="9f5674058c7c03106198eacc1aed999a05bce99f" relative="vendor/symfony/debug/Exception/ContextErrorException.php"/>
  <docblock>
    <description compact="Error Exception with Variable Context."/>
    <author value="Christian Sciberras &lt;uuf6429@gmail.com&gt;"/>
  </docblock>
  <extends full="ErrorException" namespace="" name="ErrorException"/>
  <member name="context" type="array" default="" visibility="private" line="21"/>
  <constructor name="__construct" start="23" end="27" abstract="false" final="false" static="false" visibility="public">
    <parameter name="message" byreference="false" type="{unknown}"/>
    <parameter name="code" byreference="false" type="{unknown}"/>
    <parameter name="severity" byreference="false" type="{unknown}"/>
    <parameter name="filename" byreference="false" type="{unknown}"/>
    <parameter name="lineno" byreference="false" type="{unknown}"/>
    <parameter name="context" byreference="false" type="array" default=""/>
  </constructor>
  <method name="getContext" start="32" end="35" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <return description="Array of variables that existed when the exception occurred" type="array"/>
    </docblock>
  </method>
</class>
