<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Process\Tests\ProcessFailedExceptionTest" namespace="Symfony\Component\Process\Tests" name="ProcessFailedExceptionTest" abstract="false" final="false" start="19" end="136">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/process/Tests" file="ProcessFailedExceptionTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/process/Tests/ProcessFailedExceptionTest.php" size="4313" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="eaccc7a82d1d581e86daa8ba4256bae323d600fc" relative="vendor/symfony/process/Tests/ProcessFailedExceptionTest.php"/>
  <docblock>
    <description/>
    <author value="Sebastian Marek &lt;proofek@gmail.com&gt;"/>
  </docblock>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testProcessFailedExceptionThrowsException" start="24" end="41" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="tests ProcessFailedException throws exception if the process was successful."/>
    </docblock>
  </method>
  <method name="testProcessFailedExceptionPopulatesInformationFromProcessOutput" start="47" end="90" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="tests ProcessFailedException uses information from process output to generate exception message."/>
    </docblock>
  </method>
  <method name="testDisabledOutputInFailedExceptionDoesNotPopulateOutput" start="96" end="135" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Tests that ProcessFailedException does not extract information from process output if it was previously disabled."/>
    </docblock>
  </method>
</class>
