<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Yaml\Exception\RuntimeException" namespace="Symfony\Component\Yaml\Exception" name="RuntimeException" abstract="false" final="false" start="19" end="21">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/yaml/Exception" file="RuntimeException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/yaml/Exception/RuntimeException.php" size="485" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="6d51f0c7062aee98ce4dc1077c2c2f2470d734f3" relative="vendor/symfony/yaml/Exception/RuntimeException.php"/>
  <docblock>
    <description compact="Exception class thrown when an error occurs during parsing."/>
    <author value="Romain Neutron &lt;imprec@gmail.com&gt;"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="Symfony\Component\Yaml\Exception\ExceptionInterface" namespace="Symfony\Component\Yaml\Exception" name="ExceptionInterface"/>
</class>
