<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Yaml\Exception\DumpException" namespace="Symfony\Component\Yaml\Exception" name="DumpException" abstract="false" final="false" start="19" end="21">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/yaml/Exception" file="DumpException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/yaml/Exception/DumpException.php" size="455" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="21476de0db89c3019b229ad02d7637ba72eb93d1" relative="vendor/symfony/yaml/Exception/DumpException.php"/>
  <docblock>
    <description compact="Exception class thrown when an error occurs during dumping."/>
    <author value="Fabien Potencier &lt;fabien@symfony.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Yaml\Exception\RuntimeException" namespace="Symfony\Component\Yaml\Exception" name="RuntimeException"/>
</class>
