<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Console\Event\ConsoleExceptionEvent" namespace="Symfony\Component\Console\Event" name="ConsoleExceptionEvent" abstract="false" final="false" start="23" end="67">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/console/Event" file="ConsoleExceptionEvent.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/console/Event/ConsoleExceptionEvent.php" size="1597" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="8719521e5ba940cf122ca592c6df5d78d490b620" relative="vendor/symfony/console/Event/ConsoleExceptionEvent.php"/>
  <docblock>
    <description compact="Allows to handle exception thrown in a command."/>
    <author value="Fabien Potencier &lt;fabien@symfony.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Console\Event\ConsoleEvent" namespace="Symfony\Component\Console\Event" name="ConsoleEvent"/>
  <member name="exception" visibility="private" line="25"/>
  <member name="exitCode" visibility="private" line="26"/>
  <constructor name="__construct" start="28" end="34" abstract="false" final="false" static="false" visibility="public">
    <parameter name="command" byreference="false" type="object">
      <type full="Symfony\Component\Console\Command\Command" namespace="Symfony\Component\Console\Command" name="Command"/>
    </parameter>
    <parameter name="input" byreference="false" type="object">
      <type full="Symfony\Component\Console\Input\InputInterface" namespace="Symfony\Component\Console\Input" name="InputInterface"/>
    </parameter>
    <parameter name="output" byreference="false" type="object">
      <type full="Symfony\Component\Console\Output\OutputInterface" namespace="Symfony\Component\Console\Output" name="OutputInterface"/>
    </parameter>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="exitCode" byreference="false" type="{unknown}"/>
  </constructor>
  <method name="getException" start="41" end="44" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Returns the thrown exception."/>
      <return description="The thrown exception" type="object">
        <type full="\Exception" namespace="" name="Exception"/>
      </return>
    </docblock>
  </method>
  <method name="setException" start="53" end="56" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Replaces the thrown exception.">This exception will be thrown if no response is set in the event.</description>
      <param description="The thrown exception" type="object" variable="$exception">
        <type full="\Exception" namespace="" name="Exception"/>
      </param>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </method>
  <method name="getExitCode" start="63" end="66" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Gets the exit code."/>
      <return description="The command exit code" type="int"/>
    </docblock>
  </method>
</class>
